if(EXISTS "C:/git/GTestTemplate/build-tests/test/hello_test[1]_tests.cmake")
  include("C:/git/GTestTemplate/build-tests/test/hello_test[1]_tests.cmake")
else()
  add_test(hello_test_NOT_BUILT hello_test_NOT_BUILT)
endif()
