if(EXISTS "C:/git/GTestTemplate/build-tests/test/test_main[1]_tests.cmake")
  include("C:/git/GTestTemplate/build-tests/test/test_main[1]_tests.cmake")
else()
  add_test(test_main_NOT_BUILT test_main_NOT_BUILT)
endif()
